### Kiểm tra thông tin user đã đăng nhập
GET http://localhost:8080/me
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImdtYWlsIjoibGFtdHZ0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTk0NzY5Mn0.tQOfoQba0mrXaPOvv68hC4FSIPZ1T6DS6w_LkxTMVTg