### Kiểm tra thông tin user đã đăng nhập
GET http://localhost:8080/me
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImdtYWlsIjoibGFtdHZ0QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc0MjIwMTIwNH0.cKtj6js6M7B3F_Mnz06JpnA8DF_7yrDzsQh1uJIEles
