POST http://localhost:8080/register
content-Type: application/json 

{
    "Name": "Lê Ngọc Hiếu",
	"Email": "hieuln3@gmail.com",
	"Password":"123456",
	"Phone": "0921658465",
	"Role":  "customer",
	"Orther_id":  1
}
